// actions
const FETCH_ALL_CHARACTERS = 'FETCH_ALL_CHARACTERS';
const FETCH_CHARACTER_BY_ID = 'FETCH_CHARACTER_BY_ID';

// mutations
const SET_ALL_CHARACTERS = 'SET_ALL_CHARACTERS';
const SET_CURRENT_CHARACTER = 'SET_CURRENT_CHARACTER';

export {
  FETCH_ALL_CHARACTERS,
  FETCH_CHARACTER_BY_ID,
  SET_ALL_CHARACTERS,
  SET_CURRENT_CHARACTER
};
