// actions
const FETCH_ALL_FILMS = 'FETCH_ALL_FILMS';
const FETCH_FILM_BY_ID = 'FETCH_FILM_BY_ID';

// mutations
const SET_ALL_FILMS = 'SET_ALL_FILMS';
const SET_CURRENT_FILM = 'SET_CURRENT_FILM';

export { 
  FETCH_ALL_FILMS, FETCH_FILM_BY_ID, 
  SET_ALL_FILMS, SET_CURRENT_FILM,
}